public:
  bind:
    address: 'localhost'

  cors:
    allowedOrigin: ['http://badges.elvns.com']

  rateLimit: false

  handleInternalErrors: false

private:

  gh_token: '53f218dffcd546cf81ef35488d04c829467fe7b8'
